"""Stable data contracts exchanged across backend boundaries."""

from superhp_agent.contracts.actions import AgentAction
from superhp_agent.contracts.annotation import (
    AnnotationChunkOutcome,
    AnnotationItem,
    AnnotationResult,
    ServiceIssue,
)
from superhp_agent.contracts.companion import (
    ConversationMemory,
    ConversationMemoryKind,
    ConversationMemoryStatus,
    ReadingCompanionEpisode,
    ReadingCompanionEpisodeEndReason,
    ReadingCompanionEpisodeState,
    ReadingCompanionEpisodeTrigger,
    ReadingCompanionSession,
    ReadingCompanionSessionStatus,
    ReadingContextAccessScope,
    ReadingContextSearchRequest,
    ReadingContextSearchResult,
    ReadingContextSourceMatch,
    ReadingContextSummaryMatch,
)
from superhp_agent.contracts.events import BackendEvent
from superhp_agent.contracts.llm import LLMResponse, LLMToolCall
from superhp_agent.contracts.reading import (
    AgentCard,
    ChapterReadingCheckpoint,
    ReadingProgressSnapshot,
    ReadingUnitDetail,
    ReadingUnitMeta,
)
from superhp_agent.contracts.recommendation import (
    BookCandidate,
    BookCandidateMatch,
    BookCandidateMatchResult,
    BookDifficulty,
    BookEntryKind,
    BookRecommendationHandoff,
    BookSearchQuery,
    BookSnapshot,
    OperationalReadingBand,
    ReadingDifficultyEvidence,
    ReadingDifficultyObservation,
    ReadingDifficultyState,
    ReadingLookupSummary,
    ReadingPreference,
    RecommendationAgentMessage,
    RecommendationAgentMessageRole,
    RecommendationAgentObservation,
    RecommendationAgentPhase,
    RecommendationAgentReply,
    RecommendationAgentSession,
    RecommendationOrigin,
    RecommendationOutcome,
    RecommendationOutcomeKind,
    RecommendationRequest,
)

__all__ = [
    "AgentAction",
    "AgentCard",
    "AnnotationChunkOutcome",
    "AnnotationItem",
    "AnnotationResult",
    "BackendEvent",
    "BookCandidate",
    "BookCandidateMatch",
    "BookCandidateMatchResult",
    "BookDifficulty",
    "BookEntryKind",
    "BookRecommendationHandoff",
    "BookSearchQuery",
    "BookSnapshot",
    "ChapterReadingCheckpoint",
    "ConversationMemory",
    "ConversationMemoryKind",
    "ConversationMemoryStatus",
    "LLMResponse",
    "LLMToolCall",
    "OperationalReadingBand",
    "ReadingDifficultyEvidence",
    "ReadingDifficultyObservation",
    "ReadingDifficultyState",
    "ReadingCompanionEpisode",
    "ReadingCompanionEpisodeEndReason",
    "ReadingCompanionEpisodeState",
    "ReadingCompanionEpisodeTrigger",
    "ReadingCompanionSession",
    "ReadingCompanionSessionStatus",
    "ReadingContextAccessScope",
    "ReadingContextSearchRequest",
    "ReadingContextSearchResult",
    "ReadingContextSourceMatch",
    "ReadingContextSummaryMatch",
    "ReadingLookupSummary",
    "ReadingPreference",
    "ReadingUnitDetail",
    "ReadingUnitMeta",
    "ReadingProgressSnapshot",
    "RecommendationAgentMessage",
    "RecommendationAgentMessageRole",
    "RecommendationAgentObservation",
    "RecommendationAgentPhase",
    "RecommendationAgentReply",
    "RecommendationAgentSession",
    "RecommendationOrigin",
    "RecommendationOutcome",
    "RecommendationOutcomeKind",
    "RecommendationRequest",
    "ServiceIssue",
]
